### ISSUE TITLE
eeprom address is never incremented

### ISSUE THREAD

**Issue by evgeni** [EinfachArne/Somfy_Remote#10]
since 01f81bf6eba434437a1ca4e982f2771975b8d265 the eeprom address is always 0

https://github.com/EinfachArne/Somfy_Remote/blob/ddb1c3a60590114a4c3a2dac265ba19adf884688/src/Somfy_Remote.cpp#L19
https://github.com/EinfachArne/Somfy_Remote/blob/ddb1c3a60590114a4c3a2dac265ba19adf884688/src/Somfy_Remote.cpp#L38-L47

the `if` condition is never true

**Comment by EinfachArne** [comment]
Hi, that was a mistake during late hours. https://github.com/EinfachArne/Somfy_Remote/commit/4a48e74f6bfbe7611d96b2e5ecb3c4a06ffc2d80 should fix this.

**Comment by evgeni** [comment]
Thanks! Yeah that looks correct now!
