### ISSUE TITLE
wrong pinout for ESP8266

### ISSUE THREAD

**Issue by comlit** [EinfachArne/Somfy_Remote#12]
in Somfy_Remote.cpp the gdo0Pin and gdo2Pin are set to GPIO 2 and 4 which do not correspond to pins D1 and D2 on the ESP8266
https://github.com/EinfachArne/Somfy_Remote/blob/77252ab51ad5a9025c885740348211b2c0d5aedb/src/Somfy_Remote.cpp#L149-L151

instead for the esp8366 it has to be gdo0Pin=5 and  gdo2Pin=4
![image](https://user-images.githubusercontent.com/67443177/109388205-01174900-7906-11eb-9c79-a2ac34b19661.png)

please correct me if I made a dummy mistake. I am new to this kind of stuff.

**Comment by EinfachArne** [comment]
Closed because I no longer support this project.
