### ISSUE TITLE
Debuggability

### ISSUE THREAD

**Issue by AlmightyFrog** [EinfachArne/Somfy_Remote#3]
Hi,
I am using NodeMCU ESP-32S together with D-SUN CC1101 433 MHz module and am having the "it's just not working at all" issue.
After setting my blinds into PROG mode there is just no reaction when sending "myremote/PROGRAM" at all and after some timeout blinds exit PROG mode in the end.

Looking for a way to debug the code I found out as you are using an external CC1101 library which itself does not really care about status information it is hard to do any debugging at all.

Do you have an Idea, how to best check if basic functionality is working?

I might add, that I've already:
- reviewed three times the cabeling
- hacked in a function to read direct CC1101 registers. Strangely both chip version (0x31) and txbytes (0x3A) both return "47" (or 0x2f)

Best Regards, AlmightyFrog

**Comment by engrfash** [comment]
I am having the same issue too. Help!

**Comment by engrfash** [comment]
i think i have found the issue..
after my debugging

remove

if (command == "UP" || command == "DOWN" || command == "MY" || command == "PROGRAM")
 and the two {    }

leave 
      somfy.move(command);
      EEPROM.commit();

**Comment by engrfash** [comment]
not still working

**Comment by AlmightyFrog** [comment]
@engrfash: What's your status? With regards of the command, take care to send the string as "fast" as possible but don't send line end character. Then if you also consider correct upper case spelling you should always get into that block executing the somfy request. (I just added a printf in there to see when it really was called in case of a typo)

Still, my somfy was not reacting and i do not know why. Have you done further investigations?

**Comment by AlmightyFrog** [comment]
Sadly my okish SDR is broken, so i used a RTL-SDR only. Looks like behavoir is not as expected.

The real Somfy RTS controller sends what looks like valid signals.

The ESP32 with C1101 does send quite some noise as soon as it gets power. Then if you start sending it sends forever noise (but does not spread as much on other frequencies anymore like before) which does not rely to expected protocol at all.

Not sure what is wrong there - looks like maybe either my CC1101 or the ESP32 controlling it goes wrong.

**Comment by ykrcl** [comment]
@AlmightyFrog Hi, I am having same issue with esp8266. Without using this library when I use only cc1101-Rcswitch-driver library and set frequency, transmitter mode and initialize, the orginal somfy remote doesn't work on the shutters in about 5 meters. It doesn't work with this library, also it causes orginal remote not to work until I reinitialize and put cc1101 in sleep mode. Do you have any idea fix that? the esp's power might cause, so I will try with arduino, and also with a reciever I will try Rcswitch comunucation if I get text from reciever ardunio there should be a problem about esp I think.

**Comment by ykrcl** [comment]
I will try another library I found that works with only cc1101 with Atmega328. Library uses panStamp's library to drive cc1101 and he says he tested with diffrent arduinos. If that works I will try to find a way to make that library to work with esp8266. How can I understand if my cc1101 is broken?

Library Link: https://github.com/ludodoucet/Somfy-RTS-Mysensors-7telecommandes

**Comment by EinfachArne** [comment]
Hey,

sorry for not answering for such a long time. I am sorry if you have trouble using this library but I cannot provide support regarding other libraries which are used in this one. Try to contact the developer of the CC1101 library for help.

Feel free to reopen this issue if you think I can provide changes that can make your problems go away.
