### ISSUE TITLE
please release v1.0.1

### ISSUE THREAD

**Issue by evgeni** [EinfachArne/Somfy_Remote#7]
Hi,

could you please release v1.0.1 to PlatformIO.org? It has the 1.0.0 with the EEPROM bug still listed as latest.

Thanks!

**Comment by EinfachArne** [comment]
Hi, will do it as soon as I had time to implement some other things. I hope I can release it in the next days.

**Comment by supermomo31** [comment]
Hello, look at my repo, I use your class to control my somfy with MQTT.
