### ISSUE TITLE
The Rollingcode is brocken when you reset the device

### ISSUE THREAD

**Issue by supermomo31** [EinfachArne/Somfy_Remote#8]
That is because of the EEPROM.begin executed too late.

I'm sot sure it's clean, but if work il you put the eeprom.begin under SomfyRemote::getRollingCode()

**Comment by EinfachArne** [comment]
Hi, could you please describe your problem in a bit more detail? Which device are you using and what exactly means "broken"?

Thanks in advance!

**Comment by supermomo31** [comment]
Hello, when i turn off the device, it loose the rollingcode.

**Comment by EinfachArne** [comment]
Please check if the issue is resolved.
